name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == '1on1guide-org/1on1guide-docs-ui' && !startsWith(github.event.head_commit.message, 'Release ')
    steps:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v4
    - name: Install Node.js
      timeout-minutes: 1
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      timeout-minutes: 1
      run: npm ci
    - name: Tag and release
      timeout-minutes: 3
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx gulp release
